In [60]:
import pandas as pd # data processing
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("dataset1bln.csv",usecols=['start'],  parse_dates=True)
df = pd.DataFrame(df)
#df = df.drop(df.columns[[0]], axis=1)
df1 = pd.read_csv("idpair.csv")
df1 = pd.DataFrame(df1)
#merged_data =  pd.concat(
#    map(pd.read_csv, ['MeanIntercontact_Dataset.csv', 'areaforPrepo2.csv']), ignore_index=True)
#merged_data.set_index('ID_', inplace = True)
#df2.rename(columns = {'intercontact':'MeanInt_Norm'}, inplace = True)
#df.columns = df.transpose()
df3 = pd.concat([df1, df], axis=1)
#df3.index = df3['id_pair']
#df = df.drop(df.columns[[4,5]], axis=1)
print(df)
#df1 = df.set_index(['id_pair'])
#df1.columns = pd.date_range(start= '2004-07-19 12:00:00', end='2004-08-19 12:00:00', freq='6H')

#df.to_csv('datetime.csv', index=False,    encoding='utf-8')

                   start
0    2004-07-19 12:00:00
1    2004-07-19 12:00:00
2    2004-07-20 06:00:00
3    2004-07-20 06:00:00
4    2004-07-20 06:00:00
..                   ...
304  2004-08-19 12:00:00
305  2004-08-19 12:00:00
306  2004-08-19 12:00:00
307  2004-08-19 12:00:00
308  2004-08-19 12:00:00

[309 rows x 1 columns]

In [83]:
import pandas as pd # data processing
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("datetime.csv",header=None, parse_dates=True)
result = df.transpose()
result = result.rename(columns=result.iloc[0]).drop(df.index[0])
df1 = pd.read_csv("idpair.csv")
df1 = pd.DataFrame(df1)
df3 = pd.concat([df1, result], axis=1)
df3.set_index(['id_pair'], inplace = True)
print(df3)

        2004-07-19 12:00:00 2004-07-19 12:00:00 2004-07-20 06:00:00  \
id_pair
0,1                     NaN                 NaN                 NaN
0,2                     NaN                 NaN                 NaN
0,4                     NaN                 NaN                 NaN
0,5                     NaN                 NaN                 NaN
0,6                     NaN                 NaN                 NaN
...                     ...                 ...                 ...
86,87                   NaN                 NaN                 NaN
86,88                   NaN                 NaN                 NaN
86,89                   NaN                 NaN                 NaN
87,88                   NaN                 NaN                 NaN
88,89                   NaN                 NaN                 NaN

        2004-07-20 06:00:00 2004-07-20 06:00:00 2004-07-20 12:00:00  \
id_pair
0,1                     NaN                 NaN                 NaN
0,2                     NaN                 NaN                 NaN
0,4                     NaN                 NaN                 NaN
0,5                     NaN                 NaN                 NaN
0,6                     NaN                 NaN                 NaN
...                     ...                 ...                 ...
86,87                   NaN                 NaN                 NaN
86,88                   NaN                 NaN                 NaN
86,89                   NaN                 NaN                 NaN
87,88                   NaN                 NaN                 NaN
88,89                   NaN                 NaN                 NaN

        2004-07-20 12:00:00 2004-07-20 12:00:00 2004-07-21 00:00:00  \
id_pair
0,1                     NaN                 NaN                 NaN
0,2                     NaN                 NaN                 NaN
0,4                     NaN                 NaN                 NaN
0,5                     NaN                 NaN                 NaN
0,6                     NaN                 NaN                 NaN
...                     ...                 ...                 ...
86,87                   NaN                 NaN                 NaN
86,88                   NaN                 NaN                 NaN
86,89                   NaN                 NaN                 NaN
87,88                   NaN                 NaN                 NaN
88,89                   NaN                 NaN                 NaN

        2004-07-21 06:00:00  ... 2004-08-19 12:00:00 2004-08-19 12:00:00  \
id_pair                      ...
0,1                     NaN  ...                 NaN                 NaN
0,2                     NaN  ...                 NaN                 NaN
0,4                     NaN  ...                 NaN                 NaN
0,5                     NaN  ...                 NaN                 NaN
0,6                     NaN  ...                 NaN                 NaN
...                     ...  ...                 ...                 ...
86,87                   NaN  ...                 NaN                 NaN
86,88                   NaN  ...                 NaN                 NaN
86,89                   NaN  ...                 NaN                 NaN
87,88                   NaN  ...                 NaN                 NaN
88,89                   NaN  ...                 NaN                 NaN

        2004-08-19 12:00:00 2004-08-19 12:00:00 2004-08-19 12:00:00  \
id_pair
0,1                     NaN                 NaN                 NaN
0,2                     NaN                 NaN                 NaN
0,4                     NaN                 NaN                 NaN
0,5                     NaN                 NaN                 NaN
0,6                     NaN                 NaN                 NaN
...                     ...                 ...                 ...
86,87                   NaN                 NaN                 NaN
86,88                   NaN                 NaN                 NaN
86,89                   NaN                 NaN                 NaN
87,88                   NaN                 NaN                 NaN
88,89                   NaN                 NaN                 NaN

        2004-08-19 12:00:00 2004-08-19 12:00:00 2004-08-19 12:00:00  \
id_pair
0,1                     NaN                 NaN                 NaN
0,2                     NaN                 NaN                 NaN
0,4                     NaN                 NaN                 NaN
0,5                     NaN                 NaN                 NaN
0,6                     NaN                 NaN                 NaN
...                     ...                 ...                 ...
86,87                   NaN                 NaN                 NaN
86,88                   NaN                 NaN                 NaN
86,89                   NaN                 NaN                 NaN
87,88                   NaN                 NaN                 NaN
88,89                   NaN                 NaN                 NaN

        2004-08-19 12:00:00 2004-08-19 12:00:00
id_pair
0,1                     NaN                 NaN
0,2                     NaN                 NaN
0,4                     NaN                 NaN
0,5                     NaN                 NaN
0,6                     NaN                 NaN
...                     ...                 ...
86,87                   NaN                 NaN
86,88                   NaN                 NaN
86,89                   NaN                 NaN
87,88                   NaN                 NaN
88,89                   NaN                 NaN

[2132 rows x 309 columns]

In [17]:
import pandas as pd # data processing
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("dataset1bln.csv",  parse_dates=True)
df = pd.DataFrame(df)
print(df)                  
val = df['id_colums'].to_numpy()
uniqVal = np.unique(val).tolist()
print(uniqVal)

                   start id_colums  intercontact  SpatialLoc
0    2004-07-19 12:00:00       1,3      0.000000           2
1    2004-07-19 12:00:00       4,7      0.000556           2
2    2004-07-20 06:00:00       4,5      1.662222           2
3    2004-07-20 06:00:00       4,7      1.895278           2
4    2004-07-20 06:00:00       5,7      0.230455           2
..                   ...       ...           ...         ...
304  2004-08-19 12:00:00       2,8      0.310648           2
305  2004-08-19 12:00:00      8,10      0.106422           2
306  2004-08-19 12:00:00      8,17      0.000000           2
307  2004-08-19 12:00:00      8,18      0.190000           2
308  2004-08-19 12:00:00      8,59      0.000000           2

[309 rows x 4 columns]
['0,1', '0,17', '0,18', '0,2', '0,4', '0,59', '0,6', '0,7', '0,8', '0,89', '1,17', '1,18', '1,2', '1,3', '1,4', '1,5', '1,59', '1,7', '1,8', '1,89', '10,18', '17,18', '17,59', '17,89', '2,17', '2,18', '2,4', '2,59', '2,8', '2,89', '3,8', '4,17', '4,5', '4,59', '4,7', '4,8', '5,6', '5,7', '59,87', '6,8', '7,8', '8,10', '8,17', '8,18', '8,59', '8,89']

In [18]:

0,1
0,2
0,3
0,4
0,5
0,6
0,7
0,8
0,10
0,17
0,18
0,59
0,87
0,89
1,2
1,3
1,4
1,5
1,6
1,7
1,8
1,10
1,17
1,18
1,59
1,87
1,89
2,3
2,4
2,5
2,6
2,7
2,8
2,10
2,18
2,59
2,87
2,89
3,4
3,5
3,6
3,7
3,8
3,10
3,17
3,18
3,59
3,87
3,89
4,5
4,6
4,7
4,8
4,10
4,17
4,59
4,87
4,89
5,6
5,7
5,8
5,10
5,17
5,18
5,59
5,87
5,89
6,7
6,8
6,10
6,17
6,18
6,59
6,87
6,89
7,8
7,10
7,17
7,18
7,59
7,87
7,89
8,10
8,17
8,18
8,59
8,87
8,89
10,17
10,18
10,59
10,87
10,89
17,18
17,59
17,87
17,89
18,59
18,87
18,89
59,87
59,89
87,89
2,3,4,5,6,7,8,10,17,18,59,87,89

SyntaxError: EOL while scanning string literal (<ipython-input-18-3bfa5acb6e4a>, line 2)

In [ ]:
0,1,2,3,4,5,6,7,8,10,17,18,59,87,89